---
- name: Deploy a web application
  hosts: db_and_web_server1,db_and_web_server2
  become: true
  tasks:
    - name: Update packages 
      ansible.builtin.apt:
        update_cache: yes
    - name: Install all required dependencies
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-setuptools
        - python3-dev
        - build-essential
        - python3-pip
        - python3-mysqldb

    - name: Install and Configure Database
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - mysql-server
        - mysql-client

    - name: Start Database Service
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes

    - name: Create database and database users
      community.mysql.mysql_db:
        name: employee_db
        state: present

    - name: Create a database user
      community.mysql.mysql_user:
        name: db_user
        password: Passw0rd
        priv: '*.*:ALL'
        state: present

    - name: Install Python Flask dependency
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop:
        - flask
        - flask-mysql

    - name: Copy app.py file to remote server
      ansible.builtin.copy:
        src: app.py
        dest: /opt/app.py

    - name: Starting the web server
      ansible.builtin.shell: "FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &"

    - name: Install pycharm
      apt: jjnrnijnrejve
        kjvnkjnvknekjnv
        ekjbvejbkjvndf
        nvkjenvkjnf
        kjnvkjfn
